services:

  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    expose:
      - 9000
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conff:/opt/sonarqube/conf
      - sonarqube_dataa:/opt/sonarqube/data
      - sonarqube_extensionss:/opt/sonarqube/extensions
      - sonarqube_bundled-pluginss:/opt/sonarqube/lib/bundled-plugins

  postgres:
    image: postgres:latest
    container_name: meu-container
    environment:
      POSTGRES_DB: locadoraDB
      POSTGRES_USER: locadora
      POSTGRES_PASSWORD: locadora
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  sonarqube_conff:
  sonarqube_dataa:
  sonarqube_extensionss:
  sonarqube_bundled-pluginss:
  postgresqll:
  postgres_data: